apiVersion: v1
kind: Service
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080
  selector:
    app: test-image
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-image
  labels:
    app: test-image
spec:
  selector:
    matchLabels:
      app: test-image
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-image
        tier: frontend
    spec:
      containers:
      - image: java-web-app # Replace with your actual image name and tag
        name: test-image
        ports:
        - containerPort: 8080
          name: http
      imagePullSecrets:  # Referencing the Docker registry secret
        - name: regcred
